# Generated by Django 4.1.2 on 2022-10-11 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Carro')),
                ('modelo', models.CharField(choices=[('Citroen', 'Citroen'), ('Chevrolet', 'Chevrolet'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Jeep', 'Jeep'), ('Mercedes Benz', 'Mercedes Benz'), ('Peugeot', 'Peugeot'), ('Outros', 'Outros'), ('Renault', 'Renault'), ('Toyota', 'Toyota'), ('Volkswagen', 'Volkswagen')], default='Outros', max_length=200, verbose_name='Modelo do Carro')),
                ('ano_de_fabricacao', models.CharField(choices=[('Não sabe informar o ano de fabricação', 'Não sabe informar o ano de fabricação'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], default='Não sabe informar o ano de fabricação', max_length=200, verbose_name='Ano de Fabricação')),
                ('ano_do_modelo', models.CharField(choices=[('Não sabe informar o ano do modelo', 'Não sabe informar o ano do modelo'), ('2023', '2023'), ('2022', '2022'), ('2021', '2021'), ('2020', '2020'), ('2019', '2019'), ('2018', '2018'), ('2017', '2017'), ('2016', '2016'), ('2015', '2015'), ('2014', '2014'), ('2013', '2013'), ('2012', '2012'), ('2011', '2011'), ('2010', '2010'), ('2009', '2009'), ('2008', '2008'), ('2007', '2007'), ('2006', '2006'), ('2005', '2005'), ('2004', '2004'), ('2003', '2003'), ('2002', '2002'), ('2001', '2001'), ('2000', '2000'), ('1999', '1999'), ('1998', '1998'), ('1997', '1997'), ('1996', '1996'), ('1995', '1995'), ('1994', '1994'), ('1993', '1993'), ('1992', '1992'), ('1991', '1991'), ('1990', '1990')], default='Não sabe informar o ano do modelo', max_length=200, verbose_name='Ano do Modelo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motor', models.CharField(choices=[('1.0', '1.0'), ('1.4', '1.4'), ('1.6', '1.6'), ('1.8', '1.8'), ('2.0', '2.0'), ('2.4', '2.4'), ('2.8', '2.8'), ('3.2', '3.2'), ('4.0', '4.0')], max_length=200)),
                ('motorizacao', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=200, verbose_name='Turbo')),
                ('chegou_loja', models.DateField(verbose_name='Quando chegou na loja')),
                ('saiu_loja', models.DateField(verbose_name='Quando foi vendido')),
                ('ativo', models.BooleanField(default=True, verbose_name='Tem em estoque?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['nome'],
            },
        ),
    ]
