# Generated by Django 4.1.2 on 2022-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
