# Generated by Django 4.1.2 on 2022-10-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0002_alter_carros_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='saiu_loja',
            field=models.DateField(blank=True, null=True, verbose_name='Quando foi vendido'),
        ),
    ]
