# Generated by Django 4.1.2 on 2022-10-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0004_alter_carros_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='nome',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nome do Carro'),
        ),
    ]
