# Generated by Django 4.1.2 on 2022-10-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0005_alter_carros_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carros',
            options={'ordering': ['id'], 'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterField(
            model_name='carros',
            name='ano_de_fabricacao',
            field=models.IntegerField(max_length=4, verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='ano_do_modelo',
            field=models.IntegerField(max_length=4, verbose_name='Ano do Modelo'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='modelo',
            field=models.CharField(default='Não sabe informar', max_length=200, verbose_name='Modelo do Carro'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='motor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='carros',
            name='motorizacao',
            field=models.CharField(default='Não', max_length=200, verbose_name='Turbo'),
        ),
    ]
