# Generated by Django 4.1.2 on 2022-10-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0006_alter_carros_options_alter_carros_ano_de_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ano_de_fabricacao',
            field=models.IntegerField(verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='ano_do_modelo',
            field=models.IntegerField(verbose_name='Ano do Modelo'),
        ),
    ]
