# Generated by Django 4.1.2 on 2022-10-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0007_alter_carros_ano_de_fabricacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='ativo',
            field=models.CharField(default='Sim', max_length=3, verbose_name='Tem em estoque?'),
        ),
        migrations.AlterField(
            model_name='carros',
            name='motor',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
        migrations.AlterField(
            model_name='carros',
            name='motorizacao',
            field=models.CharField(default='Não', max_length=3, verbose_name='Turbo'),
        ),
    ]
