# Generated by Django 4.1.2 on 2022-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0008_alter_carros_ativo_alter_carros_motor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='motor',
            field=models.IntegerField(),
        ),
    ]
