# Generated by Django 4.1.2 on 2022-10-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0009_alter_carros_motor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='motor',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
