# Generated by Django 4.1.2 on 2022-10-12 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0010_alter_carros_motor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carros',
            old_name='ativo',
            new_name='estoque',
        ),
    ]
