# Generated by Django 4.1.2 on 2022-10-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carros', '0011_rename_ativo_carros_estoque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carros',
            name='estoque',
            field=models.CharField(default='Sim', max_length=200, verbose_name='Tem em estoque?'),
        ),
    ]
